### ISSUE TITLE
java.lang.IllegalStateException: Binder has been finalized!

### ISSUE THREAD

**Issue by ZohaibGhafoor** [googleads/google-media-framework-android#117]
Whenever i open and close my activity. After some time i get this error.

java.lang.IllegalStateException: Binder has been finalized!
                                                                      at android.os.BinderProxy.transactNative(Native Method)
                                                                      at android.os.BinderProxy.transact(Binder.java:504)
                                                                      at android.app.IUiModeManager$Stub$Proxy.getCurrentModeType(IUiModeManager.java:157)
                                                                      at android.app.UiModeManager.getCurrentModeType(UiModeManager.java:189)
                                                                      at com.google.ads.interactivemedia.v3.impl.g.f(IMASDK:595)
                                                                      at com.google.ads.interactivemedia.v3.impl.g.l(IMASDK:67)
                                                                      at com.google.ads.interactivemedia.v3.impl.g$a.a(IMASDK:227)
                                                                      at com.google.ads.interactivemedia.v3.impl.g$a.onPostExecute(IMASDK:180)
                                                                      at android.os.AsyncTask.finish(AsyncTask.java:636)
                                                                      at android.os.AsyncTask.access$500(AsyncTask.java:177)
                                                                      at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                      at android.os.Looper.loop(Looper.java:194)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5651)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

**Comment by ypavlotsky** [comment]
I'm not seeing this in our demo application. What are the steps to reproduce this? Are you seeing it in the demo app?
