### ISSUE TITLE
java.lang.NullPointerException at com.google.android.libraries.mediaframework.layeredvideo.VideoSurfaceLayer.release(VideoSurfaceLayer.java:165)

### ISSUE THREAD

**Issue by khurram25** [googleads/google-media-framework-android#55]
receving lot of errors on multiple devices. following is stack trace

java.lang.NullPointerException
at com.google.android.libraries.mediaframework.layeredvideo.VideoSurfaceLayer.release(VideoSurfaceLayer.java:165)
at com.google.android.libraries.mediaframework.layeredvideo.SimpleVideoPlayer.release(SimpleVideoPlayer.java:354)
at com.mediaplayer.utils.ImaPlayer.destroyAdPlayer(ImaPlayer.java:639)
at com.mediaplayer.utils.ImaPlayer.resumeContent(ImaPlayer.java:676)
at com.mediaplayer.utils.ImaPlayer.access$200(ImaPlayer.java:55)
at com.mediaplayer.utils.ImaPlayer$AdListener.onAdError(ImaPlayer.java:222)
at com.google.ads.interactivemedia.v3.b.o.a(IMASDK:34)
at com.google.ads.interactivemedia.v3.b.f$a.a(IMASDK:252)
at com.google.ads.interactivemedia.v3.b.s.f(IMASDK:442)
at com.google.ads.interactivemedia.v3.b.s.a(IMASDK:178)
at com.google.ads.interactivemedia.v3.b.t.b(IMASDK:103)
at com.google.ads.interactivemedia.v3.b.t$1.shouldOverrideUrlLoading(IMASDK:47)
at android.webkit.CallbackProxy.uiOverrideUrlLoading(CallbackProxy.java:279)
at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:389)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5371)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
at dalvik.system.NativeStart.main(Native Method)

**Comment by kazo0** [comment]
In VideoSurfaceLayer

```csharp
  public void release()  { layerManager.getExoplayerWrapper().removeListener(playbackListener); }
```

Should become

```csharp
  public void release() {
    ExoplayerWrapper wrapper = layerManager.getExoplayerWrapper();
    if (wrapper != null) {
      wrapper.removeListener(playbackListener);
    }
  }
```
